### PR TITLE
Lab4 Федосеев Валера 381906-2

### PR DESCRIPTION
**Pull request by Fedoseevv26**
Fix problem with pull request destinition

### CODE REVIEW

**Comment by Fedoseevv26** [comment]
Open new pull request, rewiew please @ggladilov

**Comment by ggladilov** [comment]
> Open new pull request, rewiew please @ggladilov

Your branch failed to build:

```
llvm-project/llvm/lib/Transforms/PeepholeOptimizationCourse/ObfuscateI8AddFunction/ObfuscateI8AddFunction.cpp:3:10: fatal error: llvm/IR/Builder.h: No such file or directory
    3 | #include "llvm/IR/Builder.h"
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.

```

**Comment by Fedoseevv26** [comment]
> 

missprint in header name, rewrote it.

**Comment by ggladilov** [comment]
> > 
> 
> missprint in header name, rewrote it.

Please attach your assembly files and command lines you used to get them.

**Comment by Fedoseevv26** [comment]
[ll.zip](https://github.com/ggladilov/llvm-project/files/8842907/ll.zip)

**Comment by ggladilov** [comment]
> > 
> 
> missprint in header name, rewrote it.

It is again not compiling:

```
fatal error: llvm/Transforms/Utils/BasicBlockUnils.h: No such file or directory
    4 | #include "llvm/Transforms/Utils/BasicBlockUnils.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

How did you get your assembly files if you did not write passes correctly?

**Comment by Fedoseevv26** [comment]
Before assemble, i corrected my typeo's

**Comment by ggladilov** [comment]
> Before assemble, i corrected my typeo's

Is it building succesfully now on your end?

**Comment by Fedoseevv26** [comment]
yes

**Comment by Fedoseevv26** [comment]
yes

**Comment by ggladilov** [comment]
> yes

Removing comments is not good :) It was not building on my end.

And it is still not:

```
error: ‘IRBuidler’ was not declared in this scope; did you mean ‘IRBuilder’?
   19 |         IRBuidler<> builder(instruction);
      |         ^~~~~~~~~
      |         IRBuilder
```

**Comment by ggladilov** [comment]
Closing the PR since code is not working. Re-submit once you compile it and run.

**Pull request closed without merging**
