### PR TITLE
Лабораторная работа №4. Зайцев Михаил 381906-1

### PR DESCRIPTION
**Pull request by Zayyya**
# **DO NOT FILE A PULL REQUEST**

This repository does not accept pull requests. Please follow http://llvm.org/docs/Contributing.html#how-to-submit-a-patch for contribution to LLVM.

# **DO NOT FILE A PULL REQUEST**

### CODE REVIEW

**Comment by Zayyya** [comment]
@ggladilov  Please check

**Comment by ggladilov** [comment]
> @ggladilov Please check

Please re-check updated task definition [here](https://github.com/ggladilov/llvm-project/blob/a3de078582c71ced3e93d87ec507506071ddb969/llvm/lib/Transforms/PeepholeOptimizationCourse/Readme.md).

**Comment by Zayyya** [comment]
The function of interest to us on line 139
[llvmfiles.zip](https://github.com/ggladilov/llvm-project/files/8847015/llvmfiles.zip)

**Comment by Zayyya** [comment]
The commands I used
[commands.txt](https://github.com/ggladilov/llvm-project/files/8847019/commands.txt)

**Comment by Zayyya** [comment]
@ggladilov corrected

**Comment by ggladilov** [comment]
Pass with new manager is not registered

**Pull request closed without merging**
